---
book_repo: pivotal-cf/docs-book-partners
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master-rebrand'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs-layout-test.cfapps.io

elastic_search: true

# products:

sections:

# repos in org pivotal-cf: alphabetical
- repository:
    name: pivotal-cf/docs-altoros-aws-s3
    at_path: docs-content
  directory: partners/altoros-aws-s3
  subnav_template: altoros-aws-s3_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-cassandra
    at_path: docs-content
  directory: partners/altoros-cassandra
  subnav_template: altoros-cassandra_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-elasticsearch
    at_path: docs-content
  directory: partners/altoros-elasticsearch
  subnav_template: altoros-elasticsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-jenkins
    at_path: docs-content
  directory: partners/altoros-jenkins
  subnav_template: altoros-jenkins_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-logsearch
    at_path: docs-content
  directory: partners/altoros-logsearch
  subnav_template: altoros-logsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-appdynamics-analytics
    at_path: docs-content
  directory: partners/appdynamics-analytics
  subnav_template: appdynamics-analytics_subnav.erb
- repository:
    name: pivotal-cf/docs-appdynamics-apm
    at_path: docs-content
  directory: partners/appdynamics
  subnav_template: appdynamics-apm_subnav.erb
- repository:
    name: pivotal-cf/docs-appdynamics-platform
    at_path: docs-content
  directory: partners/appdynamics-platform
  subnav_template: appdynamics-platform_subnav.erb
- repository:
    name: pivotal-cf/docs-aqua-security
    at_path: docs-content
  directory: partners/aquasec
  subnav_template: aquasec_subnav.erb
- repository:
    name: pivotal-cf/docs-axway-apim-service-broker
    at_path: docs-content
  directory: partners/axway-apim-service-broker
  subnav_template: axway-apim-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-azure
    at_path: docs-content
  directory: partners/azure-sb
  subnav_template: azuresb_subnav.erb
- repository:
    name: pivotal-cf/docs-azure-analytics
    at_path: docs-content
  directory: partners/azure-log-analytics-nozzle
  subnav_template: azure-log-analytics-nozzle_subnav.erb
- repository:
    name: pivotal-cf/docs-bitdefender-endpoint
    at_path: docs-content
  directory: partners/bitdefender-endpoint
  subnav_template: bitdefender-endpoint_subnav.erb
- repository:
    name: pivotal-cf/docs-blackduck
    at_path: docs-content
  directory: partners/blackduck-service-broker
  subnav_template: blackduck-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-blue-medora
    at_path: docs-content
  directory: partners/blue-medora
  subnav_template: blue_medora_subnav.erb
- repository:
    name: pivotal-cf/docs-boomi-data-services
    at_path: docs-content
  directory: partners/boomi-data-services
  subnav_template: boomi-data-services_subnav.erb
- repository:
    name: pivotal-cf/docs-boomi-data-services-pks
    at_path: docs-content
  directory: partners/boomi-data-services-pks
  subnav_template: boomi-data-services-pks_subnav.erb
- repository:
    name: pivotal-cf/docs-ca-apm
    at_path: docs-content
  directory: partners/dx-apm
  subnav_template: dx-apm_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudbees
  directory: partners/cloudbees
  subnav_template: pivotal_cloudbees_service_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudbees-core-pks
    at_path: docs-content
  directory: partners/cloudbees-core
  subnav_template: cloudbees-core_subnav.erb
- repository:
    name: pivotal-cf/docs-contrast-service-broker
    at_path: docs-content
  directory: partners/contrast-service-broker
  subnav_template: contrast-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-cyberark-conjur-service-broker
    at_path: docs-content
  directory: partners/cyberark-conjur-service-broker
  subnav_template: cyberark-conjur-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-datadog
    at_path: docs-content
  directory: partners/datadog
  subnav_template: datadog_subnav.erb
- repository:
    name: pivotal-cf/docs-datadog-application-monitoring
    at_path: docs-content
  directory: partners/datadog-application-monitoring
  subnav_template: datadog-application-monitoring_subnav.erb
- repository:
    name: pivotal-cf/docs-datastax
    at_path: docs-content
  directory: partners/datastax-service-broker
  subnav_template: datastax-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-dynatrace
    at_path: docs-content
  directory: partners/dynatrace
  subnav_template: pivotal_dynatrace_service_subnav.erb
- repository:
    name: pivotal-cf/docs-dynatrace-fullstack-addon
    at_path: docs-content
  directory: partners/dynatrace-fullstack-addon
  subnav_template: dynatrace-fullstack-addon_subnav.erb
- repository:
    name: pivotal-cf/docs-ecs-service-broker
    at_path: docs-content
  directory: partners/ecs-service-broker
  subnav_template: ecs-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-engineerbetter-control-tower
    at_path: docs-content
  directory: partners/engineerbetter-control-tower
  subnav_template: engineerbetter-control-tower_subnav.erb
- repository:
    name: pivotal-cf/docs-evolven-change-analytics
    at_path: docs-content
  directory: partners/evolven-change-analytics-service-broker
  subnav_template: evolven-change-analytics-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-forgerock
    at_path: docs-content
  directory: partners/forgerock
  subnav_template: forgerock_subnav.erb
- repository:
    name: pivotal-cf/docs-gcp-stackdriver
    at_path: docs-content
  directory: partners/gcp-sdn
  subnav_template: GCP-Stackdriver_subnav.erb
- repository:
    name: pivotal-cf/docs-gitlab
  directory: partners/gitlab
  subnav_template: pivotal_gitlab_service_subnav.erb
- repository:
    name: pivotal-cf/docs-google
    at_path: docs-content
  directory: partners/gcp-sb
  subnav_template: gcpsb_subnav.erb
- repository:
    name: pivotal-cf/docs-hazelcast
    at_path: docs-content
  directory: partners/hazelcast
  subnav_template: hazelcast_subnav.erb
- repository:
    name: pivotal-cf/docs-hazelcast-jet
    at_path: docs-content
  directory: partners/hazelcast-jet
  subnav_template: hazelcast-jet_subnav.erb
- repository:
    name: pivotal-cf/docs-heimdall-database-proxy
    at_path: docs-content
  directory: partners/heimdall-database-proxy
  subnav_template: heimdall-database-proxy_subnav.erb
- repository:
    name: pivotal-cf/docs-ibm-mq-advanced
    at_path: docs-content
  directory: partners/ibm-mq-advanced
  subnav_template: ibm-mq-advanced_subnav.erb
- repository:
    name: pivotal-cf/docs-ibm-websphere-liberty-buildpack
    at_path: docs-content
  directory: partners/ibm-websphere-liberty
  subnav_template: ibm-websphere-liberty-buildpack_subnav.erb
- repository:
    name: pivotal-cf/docs-instana
    at_path: docs-content
  directory: partners/instana
  subnav_template: instana_subnav.erb
- repository:
    name: pivotal-cf/docs-jfrog
  directory: partners/jfrog
  subnav_template: pivotal_jfrog_service_subnav.erb
- repository:
    name: pivotal-cf/docs-neo4j-enterprise
    at_path: docs-content
  directory: partners/neo4j-enterprise
  subnav_template: neo4j-enterprise_subnav.erb
- repository:
    name: pivotal-cf/docs-minio
    at_path: docs-content
  directory: partners/minio
  subnav_template: minio_subnav.erb
- repository:
    name: pivotal-cf/docs-minio-greenplum
    at_path: docs-content
  directory: partners/minio-greenplum
  subnav_template: minio-greenplum_subnav.erb
- repository:
    name: pivotal-cf/docs-minio-internal-blobstore
    at_path: docs-content
  directory: partners/minio-internal-blobstore
  subnav_template: minio-internal-blobstore_subnav.erb
- repository:
    name: pivotal-cf/docs-mongodb-managed
    at_path: docs-content
  directory: partners/mongodb
  subnav_template: pivotal_mongodb_service_subnav.erb
- repository:
    name: pivotal-cf/docs-neo4j
  directory: partners/neo4j
  subnav_template: pivotal_neo4j_service_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic-dotnet-buildpack
    at_path: docs-content
  directory: partners/new-relic-dotnet-buildpack
  subnav_template: new-relic-dotnet-buildpack_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic-nozzle
    at_path: docs-content
  directory: partners/new-relic-nozzle
  subnav_template: new-relic-nozzle_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic-cluster-monitoring
    at_path: docs-content
  directory: partners/new-relic-cluster-monitoring
  subnav_template: new-relic-cluster-monitoring_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic
  directory: partners/newrelic
  subnav_template: pivotal_new_relic_service_subnav.erb
- repository:
    name: pivotal-cf/docs-pagerduty-service-broker
    at_path: docs-content
  directory: partners/pagerduty
  subnav_template: pagerduty-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-redis-enterprise-tile-manager
    at_path: docs-content
  directory: partners/redis-enterprise-tile-manager
  subnav_template: redis-enterprise-tile-manager_subnav.erb
- repository:
    name: pivotal-cf/docs-redislabs-enterprise
    at_path: docs-content
  directory: partners/redis-labs-enterprise-pack
  subnav_template: redis-labs-enterprise_subnav.erb
- repository:
    name: pivotal-cf/docs-riverbed-appinternals
    at_path: docs-content
  directory: partners/riverbed-appinternals
  subnav_template: riverbed-appinternals_subnav.erb
- repository:
    name: pivotal-cf/docs-rle-service-broker
  directory: partners/rle-service-broker
  subnav_template: pivotal_rle_service_broker.erb
- repository:
    name: pivotal-cf/docs-signalfx
    at_path: docs-content
  directory: partners/signalfx
  subnav_template: signalfx_subnav.erb
- repository:
    name: pivotal-cf/docs-signal-sciences
    at_path: docs-content
  directory: partners/signalsciences
  subnav_template: signalsciences_subnav.erb
- repository:
    name: pivotal-cf/docs-snappydata
    at_path: docs-content
  directory: partners/snappydata-service
  subnav_template: snappydata_subnav.erb
- repository:
    name: pivotal-cf/docs-snyk
    at_path: docs-content
  directory: partners/snyk
  subnav_template: snyk_subnav.erb
- repository:
    name: pivotal-cf/docs-snyk-service-broker
    at_path: docs-content
  directory: partners/snyk-service-broker
  subnav_template: snyk-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-solace-messaging
    at_path: docs-content
  directory: partners/solace-pubsub
  subnav_template: solace-pubsub_subnav.erb
- repository:
    name: pivotal-cf/docs-splunk
    at_path: docs-content
  directory: partners/splunk
  subnav_template: splunk_subnav.erb
- repository:
    name: pivotal-cf/docs-synopsys-seeker
    at_path: docs-content
  directory: partners/synopsys-seeker
  subnav_template: synopsys-seeker_subnav.erb
- repository:
    name: pivotal-cf/docs-sumologic
    at_path: docs-content
  directory: partners/sumologic-nozzle
  subnav_template: sumologic_subnav.erb
- repository:
    name: pivotal-cf/docs-tibco-businessworks
    at_path: docs-content
  directory: partners/tibco-businessworks
  subnav_template: tibco_businessworks_subnav.erb
- repository:
    name: pivotal-cf/docs-twistlock
    at_path: docs-content
  directory: partners/twistlock
  subnav_template: twistlock_subnav.erb
- repository:
    name: pivotal-cf/docs-wavefront-nozzle
    at_path: docs-content
  directory: partners/wavefront-nozzle
  subnav_template: wavefront-nozzle_subnav.erb
- repository:
    name: pivotal-cf/docs-vmware-harbor
    at_path: docs-content
  directory: partners/vmware-harbor
  subnav_template: vmware-harbor_subnav.erb
- repository:
    name: pivotal-cf/docs-wso2-api-manager
    at_path: docs-content
  directory: partners/wso2-api-manager
  subnav_template: wso2-api-manager_subnav.erb
- repository:
    name: pivotal-cf/docs-wso2-identity-server
    at_path: docs-content
  directory: partners/wso2-identity-server
  subnav_template: wso2-identity-server_subnav.erb
- repository:
    name: pivotal-cf/docs-xcrypt-archive-bbr
    at_path: docs-content
  directory: partners/xcrypt-archive
  subnav_template: xcrypt-archive-bbr_subnav.erb
- repository:
    name: pivotal-cf/docs-yugabyte-db
    at_path: docs-content
  directory: partners/yugabyte-db
  subnav_template: yugabyte-db_subnav.erb
- repository:
    name: pivotal-cf/docs-zettaset-xcrypt
    at_path: docs-content
  directory: partners/zettaset-xcrypt
  subnav_template: zettaset-xcrypt_subnav.erb

# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: partner/partials
  no_docs: true
